env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub:password"
    DOCKERHUB_USERNAME: "dockerhub:username"


phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t ethicalinsight -f src/Dockerfile src/"
      - "docker tag ethicalinsight alchemistcreative/ethicalinsight:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push alchemistcreative/ethicalinsight:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS"
version: 0.1