version: 0.1

env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub:password"
    DOCKERHUB_USERNAME: "dockerhub:username"


phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t ethicalinsight -f src/Dockerfile src/"
      - "docker tag ethicalinsight alchemistcreative/ethicalinsight:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push alchemistcreative/ethicalinsight:latest"
      - "echo Writing image definitions file"
      - "printf '[{"name":"ethicalinsight-server","imageUri":"%s"}]' alchemistcreative/ethicalinsight:latest > imagedefinitions.json"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS"

artifacts:
    files: imagedefinitions.json