#!groovy

pipeline {
  agent none
  environment {
    TARGET = 'thomas@ci.lab.alchemist.stackx'
    }

  stages {
    stage('Docker Build') {
      agent any
      steps {
        sh 'docker build -t alchemistcreative/ethicalinsight:latest -f src/Dockerfile src/'
      }
    }
    stage('Docker Push') {
      agent any
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
          sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh 'docker push alchemistcreative/ethicalinsight:latest'
        }
      }
    }
    stage('Deploy') {
      agent any
      steps {
          sh 'scp Docker/docker-compose.yml ${TARGET}:/var/ci' 
          sh 'ssh ${TARGET} docker-compose -f /var/ci/docker-compose.yml up -d'
          }
  }
}
}